on: push
name: Test and release
jobs:
  yarnInstall:
    name: yarn install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: yarn install
      uses: Borales/actions-yarn@master
      with:
        args: install
    - name: yarn test
      uses: Borales/actions-yarn@master
      with:
        args: test
    - name: yarn build
      uses: Borales/actions-yarn@master
      env:
        BUNDLESIZE_GITHUB_TOKEN: ${{ secrets.BUNDLESIZE_GITHUB_TOKEN }}
      with:
        args: build
    - name: yarn coverage
      uses: Borales/actions-yarn@master
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        args: coverage
    - name: yarn exec semantic-release
      uses: Borales/actions-yarn@master
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      with:
        args: exec semantic-release
